### ISSUE TITLE
Resolv.conf error 

### ISSUE THREAD

**Issue by Seagulls** [ShellCode33/TiredOfLinuxSetup#5]
I tried installing this with a new arch Linux iso USB but encountered the following error:

`Loading AppArmor profile`
`Warning; unable to find a suitable fs in /proc/mounts. Is it mounted?`
`Use --subdomainfs to override`
`rm: cannot remove '/etc/resolv.conf' Device or resource busy`
`[./install.sh] Error on line 22: arch-chroot /mnt rm -rf /etc/resolv.conf`
Running: mount while chrooted in gives the following entry:

`run on /etc/resolv.conf type tmpfs (rw,nosuid,nodev,relatime,mode=755,inode64)`

Unmounting and then running the relevant portions of the install script gave me a luks login then dropped me to a shell. No desktop environment.

**Comment by Seagulls** [comment]
Also when I attempt to install a desktop manager such as gnome using:

`sudo pacman -Sy gdm gnome`

Results in a dns lookup error. 

Putting the nameserver to 8.8.8.8 in /etc/resolv.conf allows me to ping google.com but doing:

`sudo pacman -Sy gdm gnome` results in:

`Running /usr/bin/pacman through local proxy http://192.168.0.1:8080`

And then basically errors relating to failed to retrieve files, 502 error.

**Comment by ShellCode33** [comment]
Hi, thanks for your report.

FYI the install script will create `stdout.log` and `stderr.log`, you might want to look into that to make sure everything went smoothly before you reach that error.

> run on /etc/resolv.conf type tmpfs (rw,nosuid,nodev,relatime,mode=755,inode64)

This is very weird, I really don't see how such a thing could happen.

This setup uses systemd-resolve for DNS, therefore `/etc/resolv.conf` must be a symlink to `/usr/lib/systemd/resolv.conf`. If you want to edit the default/fallback DNS configuration, you must look into [rootfs/etc/systemd/resolved.conf.d/default.conf](https://github.com/ShellCode33/ArchLinux-Hardened/blob/master/rootfs/etc/systemd/resolved.conf.d/default.conf) otherwise you can have a custom DNS configuration per interface using `systemd-networkd`, you will find its configuration in [rootfs/etc/systemd/network](https://github.com/ShellCode33/ArchLinux-Hardened/tree/master/rootfs/etc/systemd/network).

You can check the current DNS configuration using `resolvectl status`, you should have something like this by default:

```
Global
           Protocols: -LLMNR -mDNS +DNSOverTLS DNSSEC=yes/supported
    resolv.conf mode: static
  Current DNS Server: 9.9.9.9#dns.quad9.net
         DNS Servers: 9.9.9.9#dns.quad9.net
Fallback DNS Servers: 9.9.9.9#dns.quad9.net 1.1.1.1#cloudflare-dns.com 2620:fe::9#dns.quad9.net 2606:4700:4700::1111#cloudflare-dns.com

Link 2 (eno1)
    Current Scopes: DNS
         Protocols: -DefaultRoute -LLMNR -mDNS DNSOverTLS=opportunistic DNSSEC=yes/supported
Current DNS Server: 192.168.1.3
       DNS Servers: 192.168.1.3
        DNS Domain: ~local
```

It sounds like you didn't use the script in the intended way and made some modifications to it. You might want to share it here so I can help you further because the error you're getting doesn't make sense to me. I went through the whole installation process 2 times during the past month everything worked as expected, so I'm pretty confident the install script works in its current state.

> Running /usr/bin/pacman through local proxy http://192.168.0.1:8080

What is this IP address ? The proxy runs on `127.0.0.1:8080`. 

I do not advise you to do this but if you want you can completely bypass the network restrictions by using `sudo -g allow-internet`

**Comment by Seagulls** [comment]
> Hi, thanks for your report.
> 
> FYI the install script will create `stdout.log` ....
`

I just tried it again.

After cloning the github I make changes to the install.sh on line 294 to KEYMAP=uk

On line 297 change it to en_GB.UTF-8

Remove line 298

Change line 299 to /Europe/London

Those are the only changes to install.sh.


> > Running /usr/bin/pacman through local proxy http://192.168.0.1:8080

My mistake, I had to hand type this all out it was 127.0.0.1:8080

Stdout.log, Stderr.log (see attached)

Appreciate your help.

**Comment by ShellCode33** [comment]
I was indeed able to reproduce the error, this is a very strange one. But anyway I believe I fixed it in 8452471. You can try to pull the latest changes from master.

**Comment by Seagulls** [comment]
> I was indeed able to reproduce the error, this is a very strange one. But anyway I believe I fixed it in [8452471](https://github.com/ShellCode33/ArchLinux-Hardened/commit/84524710350ee8ebb84f7167b435bc5e7aa19134). You can try to pull the latest changes from master.

Whilst this does now install without error I have tested this a few times now to make sure I am not going crazy.

With the above changes to install.sh upon rebooting and being promoted for the luks password, entering the correct password does not unlock the drive.

I have confirmed I am entering the correct password by rebooting into the arch Linux iso installer and using:

`cryptsetup openLuks ...`

To unlock the drive. As I say I tested this multiple times with simple lower case English characters, no special characters or numbers.

**Comment by Seagulls** [comment]
> I was indeed able to reproduce the error, this is a very strange one. But anyway I believe I fixed it in [8452471](https://github.com/ShellCode33/ArchLinux-Hardened/commit/84524710350ee8ebb84f7167b435bc5e7aa19134). You can try to pull the latest changes from master.

Thank you, I can confirm that I am able to successfully boot into the sway window manager. 

Can I suggest that as part of the install.sh script you prompt the user to input their local keyboard mapping and locale? It seems to cause issues for example when unlocking the luks container it can fail if there is a mismatch between keyboard layouts.

I'm not entirely new to Linux but I'm no expert. I came across your github in my search to improve my overall desktop Linux security. I've used Ubuntu and Arch Linux with other DWM such as Gnome before.

Upon unlocking the luks partition and being presented with the desktop environment I find myself unable to do anything, right clicking on the desktop has no effect as well as right clicking in the title bar. 

I know this may sound stupid but I am learning, would it be possible for you to provide me some pointers on how I can go about configuring and using this installation to perform simple tasks? Such as opening a shell, Firefox/chrome or installing a new docker container to allow the use of say Discord? Since I see that you suggest not installing additional packages using pacman?

Appreciate the work you have done on this, I use Graphene OS on my Google pixel phone.

**Comment by ShellCode33** [comment]
> Can I suggest that as part of the install.sh script you prompt the user to input their local keyboard mapping and locale?

That is already something I thought about and it is definitely something I should do, haven't got time for it yet though.


> Upon unlocking the luks partition and being presented with the desktop environment I find myself unable to do anything, right clicking on the desktop has no effect as well as right clicking in the title bar.

This is normal Sway behavior, you can find [my Sway config in my dotfiles](https://github.com/ShellCode33/.dotfiles/blob/master/.config/sway/config). You can open a terminal using SUPER+ENTER ("super" is the Windows key on your keyboard). If you are not familiar with Tiling Window Managers, I suggest you install KDE/Gnome or any other desktop environment that suits you best. Once you've choosen the desktop environment you want, you should update your `~/.profile` to launch it. [This is the line of the `~/.profile` that launches your windows manager](https://github.com/ShellCode33/.dotfiles/blob/e35b445efa6924d33c38009e170c78a8d985b1af/.profile#L67). Therefore you might want to change the `XDG_CURRENT_DESKTOP` variable accordingly.

> I know this may sound stupid but I am learning

There are no stupid questions, only stupid answers ;)

> would it be possible for you to provide me some pointers on how I can go about configuring and using this installation to perform simple tasks? Such as opening a shell, Firefox/chrome

As I said earlier, SUPER+ENTER will spawn a terminal. SUPER+x will launch bemenu, in which you can type let's say "firefox" and hit enter, it will then spawn firefox.

> Since I see that you suggest not installing additional packages using pacman

This is a reminder more than anything else, of course there will be some packages that you will have to install on your system, and if you want to be able to reproduce your setup at some point, you should update your own [`packages/regular`](https://github.com/ShellCode33/ArchLinux-Hardened/blob/master/packages/regular) to match the packages you installed.

My setup is not really meant to be used as is, because it is my own way of doing things, I have my own shortcuts, etc. Instead you should fork my repo and change the packages to install as well as the config files of my dotfiles repo, to suit your needs. And remove anything that you don't need/want.

> I use Graphene OS on my Google pixel phone

So do I, but don't expect this Arch Linux setup to be as user friendly as Graphene can be.

**Comment by ShellCode33** [comment]
I will now close this issue as the resolv.conf bug is now fixed (thanks again for your report). If you find anything else broken don't hesitate to open other issues.

If you need more assistance with your setup you can contact me at `echo c2hlbGxjb2RlMzNAcHJvdG9uLm1lCg== | base64 -d`
